apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proctira.configmapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "proctira.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.global.nodeEnv | quote }}
  LOG_LEVEL: {{ .Values.global.logLevel | quote }}
  JWT_ISSUER: {{ .Values.config.jwtIssuer | quote }}
  JWT_AUDIENCE: {{ .Values.config.jwtAudience | quote }}
  JWT_ACCESS_TOKEN_EXPIRES_IN: {{ .Values.config.jwtAccessTokenExpiresIn | quote }}
  RATE_LIMIT_WINDOW_MS: {{ .Values.config.rateLimitWindowMs | quote }}
  RATE_LIMIT_MAX_REQUESTS: {{ .Values.config.rateLimitMaxRequests | quote }}
  TENANT_BASE_DOMAIN: {{ .Values.config.tenantBaseDomain | quote }}
  TENANT_HEADER_NAME: {{ .Values.config.tenantHeaderName | quote }}
  S3_REGION: {{ .Values.config.s3Region | quote }}
  S3_FORCE_PATH_STYLE: {{ .Values.config.s3ForcePathStyle | quote }}
