{{- if and .Values.apiGateway.enabled .Values.apiGateway.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "proctira.fullname" . }}-api-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "proctira.labels" . | nindent 4 }}
    app.kubernetes.io/name: api-gateway
spec:
  minAvailable: {{ .Values.apiGateway.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
