{{- if .Values.reportService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proctira.fullname" . }}-report-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "proctira.labels" . | nindent 4 }}
    app.kubernetes.io/name: report-service
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.reportService.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: report-service
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    {{- toYaml .Values.reportService.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: report-service
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: proctira-platform
        app.kubernetes.io/component: backend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "proctira.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: report-service
          image: {{ include "proctira.image" (dict "global" .Values.global "image" .Values.reportService.image "appVersion" .Chart.AppVersion) }}
          imagePullPolicy: {{ .Values.reportService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.reportService.service.targetPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.reportService.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "proctira.configmapName" . }}
            - secretRef:
                name: {{ include "proctira.secretName" . }}
          resources:
            {{- toYaml .Values.reportService.resources | nindent 12 }}
          {{- with .Values.reportService.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.reportService.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.reportService.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
