/**
 * apps/web/src/lib/sync/syncQueue.ts — Sync_Queue (IndexedDB)
 * (Task 54.2, Requirements 38.5, 38.6, 38.7, Design §I)
 * =====================================================================
 *
 * The Sync_Queue is the single source of truth for write operations
 * the Frontend_Shell could not deliver to the API_Gateway because the
 * user was offline. It lives at the application layer (above the
 * service worker, which `bypasses` POST/PUT/PATCH/DELETE — see
 * `apps/web/src/lib/sw/pickStrategy.ts` and `apps/web/public/sw.js`).
 *
 * Module layout:
 *
 *   • This file owns persistence: the IndexedDB schema, opening /
 *     upgrading the database, and the CRUD helpers (`enqueue`,
 *     `dequeue`, `peekAll`, `getOperation`, `persistAttempt`).
 *
 *   • `./replay.ts` owns the drain loop: submission-order iteration,
 *     exponential backoff, idempotency-header injection, and the
 *     pluggable wait/now/abort options.
 *
 *   • `./idempotencyKey.ts` owns UUID v4 generation.
 *
 * Splitting these three concerns makes each unit testable in
 * isolation and keeps `replay.ts` agnostic of the storage backend so
 * a future swap (e.g. WebLocks, OPFS) only touches this file.
 *
 * Persistence design decisions:
 *
 *   • IndexedDB is used directly with a tiny wrapper rather than the
 *     `idb` library. The API surface needed here is small enough that
 *     a hand-rolled wrapper is auditable and avoids a runtime
 *     dependency. Tests use `fake-indexeddb` to drive the same APIs
 *     in Node.
 *
 *   • Database name is namespaced per brand via the `NEXT_PUBLIC_BRAND`
 *     / `NEXT_PUBLIC_BRAND` env (default `proctira`) so multiple branded
 *     apps on the same origin do not collide.
 *
 *   • Operations are stored in a single object store with the field
 *     `createdAt` indexed so replay can iterate in submission order
 *     without sorting in JavaScript.
 *
 *   • The module is SSR-safe. The `openDatabase` helper rejects with
 *     a descriptive error if `indexedDB` is not available, so callers
 *     can guard with `typeof indexedDB !== 'undefined'`.
 */

import { generateIdempotencyKey } from './idempotencyKey';

// ─── Constants ───────────────────────────────────────────────────────────────

/** IndexedDB database name. Namespaced per brand so themed
 * deployments on the same origin do not share storage. The brand
 * default mirrors `<brand>-sync-queue` from Design §I.
 */
const DB_NAME = `${getBrand()}-sync-queue`;

/** Bumped whenever the schema changes. Triggers `onupgradeneeded`. */
const DB_VERSION = 1;

/** Single object store holding all queued operations. */
const STORE_NAME = 'operations';

/** Index on `createdAt` so replay can iterate in submission order. */
const INDEX_CREATED_AT = 'createdAt';

// ─── Public types ────────────────────────────────────────────────────────────

export type SyncOperationType = 'POST' | 'PUT' | 'PATCH' | 'DELETE';

/**
 * Persisted shape of a single queued write operation. Mirrors the 12
 * fields named in task 54.2.
 *
 * The schema intentionally separates the network-level detail
 * (`operationType`, `targetEntity`, `targetId`, `payload`) from the
 * replay-control metadata (`attemptCount`, `lastAttemptAt`,
 * `lastError`) so a future migration can split them into two stores
 * without changing the public types.
 */
export interface SyncQueueOperation {
  /** Stable UUID generated by `enqueue`. Primary key. */
  id: string;
  /** Tenant subdomain / id captured at enqueue time. */
  tenantId: string;
  /** Authenticated user id captured at enqueue time. */
  userId: string;
  /** HTTP verb to replay. */
  operationType: SyncOperationType;
  /** Logical entity (e.g. `attendance`, `student`) — for grouping in UI. */
  targetEntity: string;
  /**
   * Target identifier inside the entity. Use empty string when the
   * operation creates a new record and the id is unknown locally.
   */
  targetId: string;
  /**
   * The full request to replay. Stored as a structured object so
   * IndexedDB can serialise it natively (no JSON.parse on read).
   */
  payload: SyncOperationPayload;
  /** Sent as `Idempotency-Key` on every replay attempt. */
  idempotencyKey: string;
  /** ISO 8601 UTC timestamp of the original submission. Indexed. */
  createdAt: string;
  /** 0 before any replay attempt; bumped per failure. */
  attemptCount: number;
  /** ISO 8601 UTC of the most recent attempt, or null pre-replay. */
  lastAttemptAt: string | null;
  /** Last failure message (status + body excerpt), or null. */
  lastError: string | null;
}

/** The portion of a `fetch()` request that we persist for replay.
 * URL is required; `headers` and `body` are optional but stored
 * verbatim.
 */
export interface SyncOperationPayload {
  url: string;
  headers?: Record<string, string>;
  body?: string | null;
}

/** Input shape for `enqueue`. The id, idempotency key, and replay
 * metadata are filled in by the queue itself; everything else must
 * come from the caller.
 */
export interface EnqueueInput {
  tenantId: string;
  userId: string;
  operationType: SyncOperationType;
  targetEntity: string;
  targetId?: string;
  payload: SyncOperationPayload;
  /** Optional pre-generated UUID (lets callers do optimistic UI). */
  id?: string;
  /** Optional pre-generated idempotency key (defaults to UUID). */
  idempotencyKey?: string;
  /** Override `createdAt` (test seam). Defaults to `new Date().toISOString()`. */
  createdAt?: string;
}

// ─── Re-exports from sibling modules (preserve historical API) ───────────────

// The replay loop and its public types live in `./replay.ts` but
// historically lived here. Re-exporting keeps `import { replayAll }
// from '@/lib/sync/syncQueue'` working for callers like
// `ConnectivityProvider`.
export {
  replayAll,
  BACKOFF_SCHEDULE_MS,
  MAX_ATTEMPTS,
  REPLAY_BODY_CAPTURE_LIMIT,
  type ReplayOptions,
  type ReplayOutcome,
  type ReplayResult,
} from './replay';

// ─── Internal helpers ────────────────────────────────────────────────────────

/** Return the configured brand prefix for storage namespacing. Falls
 * back to `proctira` so SSR / tests do not need any env setup.
 */
function getBrand(): string {
  // `process.env` exists in Node and in Webpack-transpiled browser
  // bundles. We avoid `import.meta.env` here so the module remains
  // usable from both vitest and the Next.js runtime.
  if (typeof process !== 'undefined' && process.env) {
    const brand = process.env['NEXT_PUBLIC_BRAND'] ?? 'proctira';
    if (brand && brand.length > 0) return brand;
  }
  return 'proctira';
}

/**
 * Open (or upgrade) the Sync_Queue database. The caller is responsible
 * for closing the connection — we do not cache it because tests open
 * many disposable dbs and a stale handle would point to a deleted db.
 *
 * Throws if `indexedDB` is unavailable so callers can decide whether
 * to surface an error or no-op (e.g. during SSR).
 */
function openDatabase(): Promise<IDBDatabase> {
  if (typeof indexedDB === 'undefined') {
    return Promise.reject(
      new Error('Sync_Queue: indexedDB is not available in this environment'),
    );
  }
  return new Promise<IDBDatabase>((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, DB_VERSION);

    request.onupgradeneeded = () => {
      const db = request.result;
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        const store = db.createObjectStore(STORE_NAME, { keyPath: 'id' });
        // Indexed so `replayAll` iterates in submission order without
        // pulling every record into memory and sorting.
        store.createIndex(INDEX_CREATED_AT, 'createdAt', { unique: false });
      }
    };

    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error ?? new Error('IndexedDB open failed'));
    request.onblocked = () =>
      reject(new Error('Sync_Queue: open blocked by another connection'));
  });
}

/** Promisify a single IndexedDB request so we can `await` it. */
function awaitRequest<T>(request: IDBRequest<T>): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error ?? new Error('IndexedDB request failed'));
  });
}

/** Promisify a transaction's completion (for write transactions). */
function awaitTransaction(tx: IDBTransaction): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    tx.oncomplete = () => resolve();
    tx.onabort = () => reject(tx.error ?? new Error('IndexedDB transaction aborted'));
    tx.onerror = () => reject(tx.error ?? new Error('IndexedDB transaction failed'));
  });
}

/**
 * Run a callback inside a transaction with the given mode and close
 * the database afterwards. Centralising this keeps the public methods
 * focused on their per-operation logic.
 */
async function withStore<T>(
  mode: IDBTransactionMode,
  fn: (store: IDBObjectStore) => Promise<T> | T,
): Promise<T> {
  const db = await openDatabase();
  try {
    const tx = db.transaction(STORE_NAME, mode);
    const store = tx.objectStore(STORE_NAME);
    const result = await fn(store);
    if (mode !== 'readonly') {
      await awaitTransaction(tx);
    }
    return result;
  } finally {
    db.close();
  }
}

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Persist a write operation for later replay. Returns the queue id so
 * the caller can show "Queued" UI and later correlate the replay
 * outcome.
 *
 * `enqueue` does not attempt to send the request — call sites should
 * fall through to `enqueue` only when offline / heartbeat failed.
 */
export async function enqueue(input: EnqueueInput): Promise<string> {
  const id = input.id ?? generateIdempotencyKey();
  const idempotencyKey = input.idempotencyKey ?? generateIdempotencyKey();
  const createdAt = input.createdAt ?? new Date().toISOString();

  const op: SyncQueueOperation = {
    id,
    tenantId: input.tenantId,
    userId: input.userId,
    operationType: input.operationType,
    targetEntity: input.targetEntity,
    targetId: input.targetId ?? '',
    payload: input.payload,
    idempotencyKey,
    createdAt,
    attemptCount: 0,
    lastAttemptAt: null,
    lastError: null,
  };

  await withStore('readwrite', (store) => {
    store.add(op);
  });
  return id;
}

/**
 * Remove a single operation. Intended for the "Discard" action in
 * the Conflict_Resolution dialog (task 54.5) and as the success path
 * inside `replayAll`. Idempotent: deleting a missing id is not an
 * error.
 */
export async function dequeue(id: string): Promise<void> {
  await withStore('readwrite', (store) => {
    store.delete(id);
  });
}

/**
 * Read every queued operation in submission order. Used by the
 * Connectivity_Indicator badge, the sync errors tray, and the
 * conflict dialog.
 */
export async function peekAll(): Promise<SyncQueueOperation[]> {
  return withStore('readonly', async (store) => {
    const index = store.index(INDEX_CREATED_AT);
    const request = index.getAll();
    const all = await awaitRequest(request);
    // `getAll` on an index returns ascending by index key — i.e.
    // submission order. We still defensively re-sort in case a
    // platform returns ties out of order.
    return [...all].sort((a, b) =>
      a.createdAt === b.createdAt
        ? a.id.localeCompare(b.id)
        : a.createdAt.localeCompare(b.createdAt),
    );
  });
}

/**
 * Read a single operation by id, or `null` when it has been
 * dequeued. The conflict dialog uses this to refresh its view after
 * the user picks Amend or Discard.
 */
export async function getOperation(id: string): Promise<SyncQueueOperation | null> {
  return withStore('readonly', async (store) => {
    const result = await awaitRequest(store.get(id));
    return (result as SyncQueueOperation | undefined) ?? null;
  });
}

/**
 * Apply a failed-attempt update to an operation. Returns the fresh
 * record so the replay loop can decide whether to keep retrying. The
 * function is exported so `./replay.ts` can call it without
 * duplicating IndexedDB plumbing.
 *
 * Returns `null` when the record has been deleted out from under us
 * (for example because the user clicked Discard mid-replay). The
 * caller is expected to treat the absent record as a signal to exit
 * its retry loop.
 */
export async function persistAttempt(
  id: string,
  attemptCount: number,
  lastAttemptAt: string,
  lastError: string,
): Promise<SyncQueueOperation | null> {
  return withStore('readwrite', async (store) => {
    const existing = (await awaitRequest(store.get(id))) as
      | SyncQueueOperation
      | undefined;
    if (!existing) return null;
    const updated: SyncQueueOperation = {
      ...existing,
      attemptCount,
      lastAttemptAt,
      lastError,
    };
    store.put(updated);
    return updated;
  });
}

// ─── Test seam ───────────────────────────────────────────────────────────────

/**
 * Wipe the entire queue. Exported only for tests and the
 * "Discard all queued operations" admin action. Do NOT call from
 * normal product code — Sync_Queue contents are user data.
 */
export async function _resetForTests(): Promise<void> {
  if (typeof indexedDB === 'undefined') return;
  await new Promise<void>((resolve, reject) => {
    const req = indexedDB.deleteDatabase(DB_NAME);
    req.onsuccess = () => resolve();
    req.onerror = () => reject(req.error ?? new Error('deleteDatabase failed'));
    req.onblocked = () => resolve();
  });
}
