-- PRC-L186: forward replacement for 084's split privilege sync (W1-DATA-11).
--
-- 084 guarded the privilege sync with a DO block whose RETURN only exited that
-- block, so the following top-level ALTER DEFAULT PRIVILEGES ... proctira_app
-- statements still ran and failed when the runtime role was missing. 084 is
-- left untouched (checksum-stable). This file re-runs the same classified sync
-- as ONE role-guarded DO block, generated by
-- tools/scripts/runtime-table-privileges-lib.mjs generateSyncSql() from
-- db/runtime-table-privileges.json at the time of writing. The authoritative
-- catalog sync still runs after every apply via apply-runtime-table-privileges.sh,
-- so later catalog changes do not require editing this file.
--
-- Data safety: privileges only, no data touched. Revoke-then-grant runs in the
-- runner's single transaction, so the runtime role never observes the stripped
-- state. Idempotent; a NOTICE and no-op when proctira_app does not exist.
--
-- Rollback: not needed (re-asserts 084's intended grants); the catalog sync is
-- the source of truth.
-- Generated by tools/scripts/runtime-table-privileges-lib.mjs (W1-DATA-11)
-- Do not grant via ALTER DEFAULT PRIVILEGES — every table is classified.

DO $$
DECLARE
  t TEXT;
  r RECORD;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'proctira_app') THEN
    RAISE NOTICE 'W1-DATA-11: proctira_app missing — skip privilege sync';
    RETURN;
  END IF;

  -- Remove blanket future-table DML (050 historical DEFAULT PRIVILEGES).
  ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM proctira_app;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE ALL ON TABLES FROM proctira_app;

  ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO proctira_app;

  -- Fail closed: strip every current public table privilege for runtime.
  FOR r IN
    SELECT c.relname AS name
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p')
  LOOP
    EXECUTE format('REVOKE ALL ON TABLE %I FROM proctira_app', r.name);
    EXECUTE format('REVOKE ALL ON TABLE %I FROM PUBLIC', r.name);
  END LOOP;

  -- class: denied (NONE)
  FOREACH t IN ARRAY ARRAY[
    '_prisma_migrations',
    'grade_change_audit_orphan_quarantine',
    'schema_migrations'
  ]
  LOOP
    IF to_regclass(format('public.%I', t)) IS NOT NULL THEN
      -- denied: leave revoked
      NULL;
    END IF;
  END LOOP;

  -- class: select_insert (SELECT, INSERT)
  FOREACH t IN ARRAY ARRAY[
    'insights_ui_geo_features',
    'insights_ui_indicators',
    'insights_ui_templates'
  ]
  LOOP
    IF to_regclass(format('public.%I', t)) IS NOT NULL THEN
      EXECUTE format('GRANT SELECT, INSERT ON TABLE %I TO proctira_app', t);
    END IF;
  END LOOP;

  -- class: append_only (SELECT, INSERT)
  FOREACH t IN ARRAY ARRAY[
    'admission_form_configurations',
    'audit_log_archive',
    'audit_log_entries',
    'examination_publication_versions',
    'fee_ledger_entries',
    'institution_repair_requests',
    'transcript_issuances',
    'workflow_transition_audit'
  ]
  LOOP
    IF to_regclass(format('public.%I', t)) IS NOT NULL THEN
      EXECUTE format('GRANT SELECT, INSERT ON TABLE %I TO proctira_app', t);
    END IF;
  END LOOP;

  -- class: trigger_owned (SELECT)
  FOREACH t IN ARRAY ARRAY[
    'enrollment_history',
    'grade_change_audit'
  ]
  LOOP
    IF to_regclass(format('public.%I', t)) IS NOT NULL THEN
      EXECUTE format('GRANT SELECT ON TABLE %I TO proctira_app', t);
    END IF;
  END LOOP;

  -- class: dml (SELECT, INSERT, UPDATE, DELETE)
  FOREACH t IN ARRAY ARRAY[
    'academic_calendar_events',
    'academic_periods',
    'academic_rollover_runs',
    'admission_applications',
    'admission_enquiries',
    'admission_interview_bookings',
    'admission_interview_slots',
    'admission_offers',
    'admission_waitlist_entries',
    'assessment_items',
    'assessment_outcomes',
    'assessment_results',
    'attendance_audit',
    'attendance_device_keys',
    'attendance_ingest_events',
    'attendance_leave_requests',
    'attendance_regularisation_requests',
    'audit_chain_heads',
    'audit_retention_configs',
    'bell_periods',
    'bell_schedules',
    'board_codes',
    'board_export_jobs',
    'boards',
    'class_rank_snapshots',
    'classes',
    'comments_bank',
    'comms_campaigns',
    'comms_circular_acks',
    'comms_circulars',
    'comms_delivery_log',
    'comms_emergency_blasts',
    'control_plane_documents',
    'counselling_sessions',
    'credit_rules',
    'developer_portal_accounts',
    'developer_portal_api_keys',
    'developer_portal_webhook_deliveries',
    'developer_portal_webhook_signing_secrets',
    'developer_portal_webhooks',
    'enquiry_followups',
    'enrollments',
    'etl_pipeline_runs',
    'etl_pipelines',
    'exam_invigilators',
    'exam_marks_entries',
    'exam_reevaluation_requests',
    'exam_seating',
    'exam_sessions',
    'examination_academic_records',
    'examination_candidate_registrations',
    'examination_candidates',
    'examination_document_jobs',
    'examination_publications',
    'examination_result_analyses',
    'examinations',
    'fee_concessions',
    'fee_credit_notes',
    'fee_reconciliation_batches',
    'fee_reconciliation_rows',
    'fee_refunds',
    'fee_reminder_send_audits',
    'fee_reminder_suppressions',
    'fee_structure_components',
    'fee_structure_instalments',
    'fee_structures',
    'fee_write_offs',
    'gate_passes',
    'geographic_areas',
    'gpa_snapshots',
    'grade_entries',
    'grades',
    'grading_scale_bands',
    'grading_scales',
    'grading_schemes',
    'guardian_custody_restrictions',
    'guardian_household_members',
    'guardian_households',
    'guardian_student_custody',
    'health_accommodation_plans',
    'health_allergies',
    'health_conditions',
    'health_diagnoses',
    'health_insurance',
    'health_measurements',
    'health_nurse_incidents',
    'health_phi_access_log',
    'health_phi_break_glass',
    'health_referrals',
    'health_screening_programs',
    'health_special_needs_assessments',
    'health_vaccinations',
    'hostel_assignments',
    'hostel_attendance',
    'hostel_beds',
    'hostel_blocks',
    'hostel_fee_structures',
    'hostel_leaves',
    'hostel_rooms',
    'hostel_visitors',
    'hostels',
    'hr_appraisal_templates',
    'hr_appraisals',
    'hr_certifications',
    'hr_training_attendance',
    'hr_training_programs',
    'hr_training_sessions',
    'insights_ui_import_jobs',
    'insights_ui_runs',
    'institution_condition_options',
    'institution_infrastructure',
    'institution_subjects',
    'institutions',
    'keeps',
    'learning_outcomes',
    'lesson_plans',
    'library_copies',
    'library_fine_policies',
    'library_fines',
    'library_holds',
    'library_items',
    'library_loans',
    'lms_assignment_files',
    'lms_assignments',
    'lms_content_items',
    'lms_discussion_posts',
    'lms_discussions',
    'lms_lesson_resources',
    'lms_lessons',
    'lms_module_items',
    'lms_modules',
    'lms_practice_attempts',
    'lms_question_bank',
    'lms_quiz_questions',
    'lms_rubric_criteria',
    'lms_rubric_scores',
    'lms_rubrics',
    'lms_skill_mastery',
    'lms_skills',
    'lms_submissions',
    'merit_list_entries',
    'merit_lists',
    'mess_menu_items',
    'mess_plans',
    'mess_subscriptions',
    'notification_devices',
    'notification_preferences',
    'notifications',
    'parent_child_links',
    'parent_consents',
    'parent_fee_invoices',
    'parent_fee_payments',
    'parent_fee_plans',
    'parent_fee_receipts',
    'parent_message_threads',
    'parent_messages',
    'privacy_anonymization_jobs',
    'privacy_correction_requests',
    'privacy_erasure_requests',
    'privacy_legal_holds',
    'privacy_tenant_offboard_jobs',
    'refresh_tokens',
    'report_artifacts',
    'report_card_institution_branding',
    'report_card_jobs',
    'report_card_teacher_comments',
    'report_card_templates',
    'report_definitions',
    'report_runs',
    'report_schedules',
    'rooms',
    'scholarship_application_documents',
    'scholarship_applications',
    'scholarship_compliance_records',
    'scholarship_disbursements',
    'scholarship_fee_outbox',
    'scholarship_programs',
    'search_index_documents',
    'seat_matrix',
    'section_enrollments',
    'section_meetings',
    'sections',
    'staff',
    'staff_assignments',
    'staff_attendance',
    'staff_contracts',
    'staff_hr_attendance',
    'staff_leave_balances',
    'staff_leave_requests',
    'staff_payroll_ledger_entries',
    'staff_payroll_lines',
    'staff_payroll_runs',
    'staff_qualifications',
    'student_admission_counters',
    'student_attendance',
    'student_consents',
    'student_discipline_incidents',
    'student_documents',
    'student_import_jobs',
    'student_merges',
    'student_photos',
    'student_siblings',
    'students',
    'subjects',
    'substitutions',
    'syllabus_units',
    'tenant_theme_drafts',
    'tenant_theme_versions',
    'tenants',
    'timetable_generation_jobs',
    'timetable_teacher_absences',
    'transactional_outbox',
    'transcript_signing_keys',
    'transfer_records',
    'transport_alert_rules',
    'transport_alerts',
    'transport_bus_attendance',
    'transport_driver_assignments',
    'transport_fee_links',
    'transport_fee_structures',
    'transport_gps_pings',
    'transport_routes',
    'transport_stops',
    'transport_student_assignments',
    'transport_vehicle_devices',
    'transport_vehicles',
    'unit_coverage',
    'user_sessions',
    'workflow_cases',
    'workflow_definitions',
    'workflow_instances',
    'workflow_ui_approvals',
    'workflow_ui_definitions',
    'workflow_ui_instances'
  ]
  LOOP
    IF to_regclass(format('public.%I', t)) IS NOT NULL THEN
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE %I TO proctira_app', t);
    END IF;
  END LOOP;

  -- Sequences for INSERT into non-denied tables.
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO proctira_app;
END $$;
