-- PRC-H052: durable, shared store for generated examination document PDFs.
--
-- Generated admit-card / result-certificate PDFs were kept in a process-local
-- in-memory Map, so in queue mode the worker generated bytes the API process
-- never had (download → 404), and single-process restarts lost them while the
-- job row still said 'completed'. This table is the durable backing store:
-- PgDocumentBlobStore writes the bytes here (keyed by the storage key, whose
-- 2nd path segment is the tenant id) and the API reads them back.
--
-- New tenant table: ENABLE + FORCE ROW LEVEL SECURITY with the standard
-- tenant_isolation policy. The store binds app.tenant_id (derived from the key)
-- before every read/write. Transactional DDL, additive and idempotent.
-- Rollback: forward-only; dropping the table loses stored PDFs — drain first.

CREATE TABLE IF NOT EXISTS examination_document_blobs (
  storage_key TEXT PRIMARY KEY,
  tenant_id   UUID NOT NULL REFERENCES tenants(id),
  content     BYTEA NOT NULL,
  byte_size   INTEGER NOT NULL CHECK (byte_size >= 0),
  checksum    TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS examination_document_blobs_tenant_idx
  ON examination_document_blobs (tenant_id, created_at);

ALTER TABLE examination_document_blobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE examination_document_blobs FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON examination_document_blobs;
CREATE POLICY tenant_isolation ON examination_document_blobs
  FOR ALL
  USING (tenant_id::text = NULLIF(current_setting('app.tenant_id', true), ''))
  WITH CHECK (tenant_id::text = NULLIF(current_setting('app.tenant_id', true), ''));

COMMENT ON TABLE examination_document_blobs IS
  'PRC-H052 durable store for generated examination document PDFs; shared by API and worker.';

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'proctira_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE examination_document_blobs TO proctira_app;
  END IF;
END $$;

INSERT INTO schema_migrations (filename)
VALUES ('125_examination_document_blobs.sql')
ON CONFLICT (filename) DO NOTHING;
