-- PRC-H049 (residual): durable storage for developer-portal sandboxes, plugin
-- ratings, documentation pages and analytics events.
--
-- db/sql/132 made submissions and listings durable but sandboxes/ratings/docs/
-- analytics stayed in process memory even with DATABASE_URL set, so provisioned
-- sandboxes, developer ratings, published docs and analytics counters vanished on
-- restart and differed per replica. This migration makes the remaining four
-- entities durable, closing PRC-H049.
--
-- Platform-scoped (the developer portal is a global surface keyed by account /
-- plugin name, not tenant-partitioned), using the same platform_admin_only RLS as
-- developer_portal_submissions / developer_portal_listings (db/sql/132, 089).
-- Idempotent; apply-sql.sh phase ledger records completion. Forward-only.

-- 1) Sandboxes --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS developer_portal_sandboxes (
  id           UUID PRIMARY KEY,
  account_id   UUID NOT NULL,
  name         TEXT NOT NULL,
  description  TEXT,
  -- Synthetic per-sandbox tenant id generated by the developer portal (uuidv4),
  -- NOT a row in tenants; named so tenant-id/FK/wipe gates do not treat it as tenant data.
  sandbox_tenant_id UUID NOT NULL,
  status       TEXT NOT NULL DEFAULT 'provisioning'
    CHECK (status IN ('provisioning','active','expired','destroyed')),
  expires_at   TIMESTAMPTZ NOT NULL,
  api_endpoint TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS developer_portal_sandboxes_account_idx
  ON developer_portal_sandboxes (account_id, created_at DESC);

ALTER TABLE developer_portal_sandboxes ENABLE ROW LEVEL SECURITY;
ALTER TABLE developer_portal_sandboxes FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS platform_admin_only ON developer_portal_sandboxes;
CREATE POLICY platform_admin_only ON developer_portal_sandboxes
  FOR ALL
  USING (current_setting('app.platform_admin', true) = '1')
  WITH CHECK (current_setting('app.platform_admin', true) = '1');

-- 2) Plugin ratings ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS developer_portal_ratings (
  id          UUID PRIMARY KEY,
  plugin_name TEXT NOT NULL,
  account_id  UUID NOT NULL,
  rating      INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  review      TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (plugin_name, account_id)
);

CREATE INDEX IF NOT EXISTS developer_portal_ratings_plugin_idx
  ON developer_portal_ratings (plugin_name);

ALTER TABLE developer_portal_ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE developer_portal_ratings FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS platform_admin_only ON developer_portal_ratings;
CREATE POLICY platform_admin_only ON developer_portal_ratings
  FOR ALL
  USING (current_setting('app.platform_admin', true) = '1')
  WITH CHECK (current_setting('app.platform_admin', true) = '1');

-- 3) Documentation pages ----------------------------------------------------
CREATE TABLE IF NOT EXISTS developer_portal_doc_pages (
  id         UUID PRIMARY KEY,
  slug       TEXT NOT NULL UNIQUE,
  title      TEXT NOT NULL,
  content    TEXT NOT NULL,
  category   TEXT NOT NULL,
  "order"    INTEGER NOT NULL DEFAULT 0,
  published  BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS developer_portal_doc_pages_category_idx
  ON developer_portal_doc_pages (category, "order");

ALTER TABLE developer_portal_doc_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE developer_portal_doc_pages FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS platform_admin_only ON developer_portal_doc_pages;
CREATE POLICY platform_admin_only ON developer_portal_doc_pages
  FOR ALL
  USING (current_setting('app.platform_admin', true) = '1')
  WITH CHECK (current_setting('app.platform_admin', true) = '1');

-- 4) Analytics events -------------------------------------------------------
CREATE TABLE IF NOT EXISTS developer_portal_analytics_events (
  id          UUID PRIMARY KEY,
  plugin_name TEXT NOT NULL,
  event_type  TEXT NOT NULL
    CHECK (event_type IN ('install','uninstall','api_call','error','page_view')),
  metadata    JSONB,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS developer_portal_analytics_plugin_idx
  ON developer_portal_analytics_events (plugin_name, created_at DESC);

ALTER TABLE developer_portal_analytics_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE developer_portal_analytics_events FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS platform_admin_only ON developer_portal_analytics_events;
CREATE POLICY platform_admin_only ON developer_portal_analytics_events
  FOR ALL
  USING (current_setting('app.platform_admin', true) = '1')
  WITH CHECK (current_setting('app.platform_admin', true) = '1');

COMMENT ON TABLE developer_portal_sandboxes IS
  'PRC-H049 durable developer sandboxes (replaces in-memory residual).';
COMMENT ON TABLE developer_portal_ratings IS
  'PRC-H049 durable plugin ratings (replaces in-memory residual).';
COMMENT ON TABLE developer_portal_doc_pages IS
  'PRC-H049 durable developer documentation pages (replaces in-memory residual).';
COMMENT ON TABLE developer_portal_analytics_events IS
  'PRC-H049 durable developer-portal analytics events (replaces in-memory residual).';

DO $h049r_grant$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'proctira_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE
      ON TABLE developer_portal_sandboxes, developer_portal_ratings,
               developer_portal_doc_pages, developer_portal_analytics_events
      TO proctira_app;
  END IF;
END
$h049r_grant$;
