/**
 * Runtime-visible relation contracts for raw PostgreSQL adapters.
 *
 * Relation checks catch missing objects; the global migration marker in
 * schema-readiness.ts catches ALTER-only and integrity-only migration gaps.
 */
export const DATABASE_SCHEMA_CONTRACTS = {
  insightsUi: [
    'public.insights_ui_templates',
    'public.insights_ui_runs',
    'public.insights_ui_import_jobs',
    'public.insights_ui_indicators',
    'public.insights_ui_geo_features',
  ],
  workflowUi: [
    'public.workflow_ui_definitions',
    'public.workflow_ui_instances',
    'public.workflow_ui_approvals',
  ],
  reportCards: [
    'public.report_card_templates',
    'public.report_card_teacher_comments',
    'public.report_card_institution_branding',
    'public.report_card_jobs',
  ],
  communicationCirculars: [
    'public.comms_campaigns',
    'public.comms_emergency_blasts',
    'public.comms_circulars',
    'public.comms_circular_acks',
    'public.comms_delivery_log',
  ],
  communication: ['public.comms_campaigns', 'public.comms_emergency_blasts'],
  developerPortalApiKeys: ['public.developer_portal_api_keys'],
  developerPortalDurable: [
    'public.developer_portal_accounts',
    'public.developer_portal_webhooks',
    'public.developer_portal_webhook_deliveries',
  ],
  fees: [
    'public.parent_fee_plans',
    'public.parent_fee_invoices',
    'public.parent_fee_payments',
    'public.parent_fee_receipts',
    'public.fee_ledger_entries',
    'public.fee_structures',
    'public.fee_structure_components',
    'public.fee_structure_instalments',
    'public.fee_concessions',
    'public.fee_refunds',
    'public.fee_reconciliation_batches',
    'public.fee_reconciliation_rows',
    'public.fee_reminder_suppressions',
    'public.fee_reminder_send_audits',
    'public.fee_credit_notes',
    'public.fee_write_offs',
  ],
  healthBreakGlass: ['public.health_phi_break_glass', 'public.health_phi_access_log'],
  healthCounselling: ['public.counselling_sessions'],
  healthNurseIncidents: ['public.health_nurse_incidents'],
  healthPhi: [
    'public.health_measurements',
    'public.health_allergies',
    'public.health_conditions',
    'public.health_vaccinations',
    'public.health_insurance',
    'public.health_screening_programs',
  ],
  healthSpecialNeeds: [
    'public.health_special_needs_assessments',
    'public.health_diagnoses',
    'public.health_referrals',
    'public.health_accommodation_plans',
    'public.health_phi_access_log',
  ],
  hostel: [
    'public.hostels',
    'public.hostel_blocks',
    'public.hostel_rooms',
    'public.hostel_beds',
    'public.hostel_assignments',
    'public.hostel_leaves',
    'public.hostel_visitors',
    'public.mess_plans',
    'public.mess_menu_items',
    'public.mess_subscriptions',
    'public.gate_passes',
    'public.hostel_fee_structures',
    'public.hostel_attendance',
  ],
  institutionInfrastructure: [
    'public.institution_infrastructure',
    'public.institution_condition_options',
  ],
  library: [
    'public.library_items',
    'public.library_loans',
    'public.library_copies',
    'public.library_holds',
    'public.library_fine_policies',
    'public.library_fines',
  ],
  lms: [
    'public.lms_skills',
    'public.lms_assignments',
    'public.lms_quiz_questions',
    'public.lms_submissions',
    'public.lms_skill_mastery',
    'public.lms_practice_attempts',
    'public.lms_question_bank',
    'public.lms_rubrics',
    'public.lms_rubric_criteria',
    'public.lms_rubric_scores',
    'public.lms_assignment_files',
    'public.lms_discussions',
    'public.lms_discussion_posts',
    'public.lms_content_items',
    'public.lms_lessons',
    'public.lms_lesson_resources',
    'public.lms_modules',
    'public.lms_module_items',
  ],
  notifications: ['public.notifications'],
  parentPortal: [
    'public.parent_child_links',
    'public.parent_message_threads',
    'public.parent_messages',
    'public.parent_consents',
    'public.parent_fee_plans',
    'public.parent_fee_invoices',
    'public.parent_fee_payments',
    'public.parent_fee_receipts',
    'public.guardian_households',
    'public.guardian_household_members',
    'public.guardian_student_custody',
    'public.guardian_custody_restrictions',
  ],
  privacy: [
    'public.privacy_legal_holds',
    'public.privacy_erasure_requests',
    'public.privacy_correction_requests',
    'public.privacy_anonymization_jobs',
    'public.privacy_tenant_offboard_jobs',
  ],
  registration: [
    'public.admission_applications',
    'public.admission_form_configurations',
    'public.institutions',
    'public.geographic_areas',
    'public.classes',
  ],
  admissionsPipeline: [
    'public.admission_enquiries',
    'public.enquiry_followups',
    'public.seat_matrix',
    'public.merit_lists',
    'public.merit_list_entries',
    'public.admission_offers',
  ],
  reports: [
    'public.report_definitions',
    'public.report_artifacts',
    'public.report_schedules',
    'public.report_runs',
  ],
  scholarships: [
    'public.scholarship_programs',
    'public.scholarship_applications',
    'public.scholarship_disbursements',
    'public.scholarship_compliance_records',
  ],
  hrAppraisalTraining: [
    'public.hr_appraisal_templates',
    'public.hr_appraisals',
    'public.hr_training_programs',
    'public.hr_training_sessions',
    'public.hr_training_attendance',
    'public.hr_certifications',
  ],
  staffHrOps: [
    'public.staff_contracts',
    'public.staff_qualifications',
    'public.staff_hr_attendance',
    'public.staff_payroll_runs',
    'public.staff_payroll_lines',
    'public.staff_payroll_ledger_entries',
  ],
  staffLeave: ['public.staff_leave_requests', 'public.staff_leave_balances'],
  transport: [
    'public.transport_routes',
    'public.transport_stops',
    'public.transport_vehicles',
    'public.transport_driver_assignments',
    'public.transport_student_assignments',
    'public.transport_vehicle_devices',
    'public.transport_gps_pings',
    'public.transport_bus_attendance',
    'public.transport_alert_rules',
    'public.transport_alerts',
    'public.transport_fee_structures',
    'public.transport_fee_links',
  ],
  workflowEngine: [
    'public.workflow_definitions',
    'public.workflow_instances',
    'public.workflow_transition_audit',
    'public.workflow_cases',
  ],
} as const satisfies Record<string, readonly string[]>;

export type DatabaseSchemaContractName = keyof typeof DATABASE_SCHEMA_CONTRACTS;
